
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class TugasBB extends javax.swing.JFrame {
    
    String temp ="";
    Double h, w, Res;
    
    public TugasBB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfRes = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfD2 = new javax.swing.JTextField();
        tfTinggi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        bClose = new javax.swing.JButton();
        bHitung = new javax.swing.JButton();
        bCoba = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfBB = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfD1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 30, 110, 30);

        jLabel2.setText("Berat Badan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 160, 70, 20);

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 80, 70, 20);

        tfRes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(tfRes);
        tfRes.setBounds(250, 290, 60, 30);

        jLabel4.setText("Tinggi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 120, 40, 20);

        tfD2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(tfD2);
        tfD2.setBounds(70, 400, 270, 30);

        tfTinggi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(tfTinggi);
        tfTinggi.setBounds(160, 120, 50, 30);

        jLabel5.setText("kg");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 280, 50, 40);

        jLabel6.setText("cm");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 110, 50, 40);

        jLabel7.setText("Jenis Kelamin");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 210, 90, 20);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Perempuan");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(270, 200, 100, 40);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Laki-Laki");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(180, 200, 100, 40);

        bClose.setText("Keluar");
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });
        getContentPane().add(bClose);
        bClose.setBounds(270, 250, 70, 30);

        bHitung.setText("Hitung");
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });
        getContentPane().add(bHitung);
        bHitung.setBounds(70, 250, 70, 30);

        bCoba.setText("Coba Lagi");
        bCoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCobaActionPerformed(evt);
            }
        });
        getContentPane().add(bCoba);
        bCoba.setBounds(160, 250, 90, 30);

        jLabel8.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 290, 190, 30);

        tfBB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBBActionPerformed(evt);
            }
        });
        getContentPane().add(tfBB);
        tfBB.setBounds(160, 160, 50, 30);

        jLabel9.setText("kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 150, 50, 40);

        jLabel10.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 330, 200, 20);

        tfNama.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(tfNama);
        tfNama.setBounds(160, 80, 140, 30);

        tfD1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(tfD1);
        tfD1.setBounds(70, 360, 270, 30);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(51, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 470);

        setBounds(0, 0, 420, 507);
    }// </editor-fold>//GEN-END:initComponents

    private void bCobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCobaActionPerformed
        tfNama.setText("");
        tfD1.setText("");
        tfBB.setText("");
        tfTinggi.setText("");
        tfRes.setText("");
        tfD2.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_bCobaActionPerformed

    private void tfBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBBActionPerformed

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        dispose();
    }//GEN-LAST:event_bCloseActionPerformed

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        if(tfNama.getText().equals("")||
            tfBB.getText().equals("")||
            tfTinggi.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Kotak isian harus diisi semua");
        } else if(jRadioButton1.isSelected()||jRadioButton2.isSelected()) {
            try {
                Proses();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Masukan ada yang salah");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Anda harus memilih jenis kelamin");
        }
    }//GEN-LAST:event_bHitungActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        //radioButton Laki-laki
        jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // radioButton Perempuan
        jRadioButton2.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TugasBB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TugasBB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TugasBB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TugasBB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TugasBB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JButton bCoba;
    private javax.swing.JButton bHitung;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField tfBB;
    private javax.swing.JTextField tfD1;
    private javax.swing.JTextField tfD2;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfRes;
    private javax.swing.JTextField tfTinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        h = Double.valueOf(tfTinggi.getText());
        w = Double.valueOf(tfBB.getText());
        
        if (jRadioButton1.isSelected()) {
            Res = (h - 104) * 1;
        } else if (jRadioButton2.isSelected()) {
            Res = (h - 100) * 1;
        }
        temp = Double.toString(Res.intValue());
        
        if (Res < w) {
            tfRes.setText(temp);
            tfD1.setText("Maaf "+tfNama.getText()+", Sepertinya anda Overweight");
            tfD2.setText("Banyaklah berolahraga dan hindari makanan berkolestrol");
        } else if (Res > w) {
            tfRes.setText(temp);
            tfD1.setText("Maaf "+tfNama.getText()+", Sepertinya anda Underweight");
            tfD2.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
        } else {
            tfRes.setText(temp);
            tfD1.setText("Hei "+tfNama.getText()+", Berat badan anda sudah ideal");
            tfD2.setText("Tetap jaga pola makan teratur dan gaya hidup sehat");
        }
    }
}
